version: '3.9'
services:
  web:
    ports:
    - 80
    environment:
    - TITLE=Kedd mingyart kave szunte ....
    - COLOR=tan
    - BODY=<iframe src="https://giphy.com/embed/pzryvxGeykOxeC0fWb" width="480" height="400" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/garfield-cat-coffee-pzryvxGeykOxeC0fWb">via GIPHY</a></p>
    image: web:alpine
    # build: .

  mydb:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=secret
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    - vipdb:/var/lib/postgresql/data
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080

volumes:
  vipdb: