version: '3.9'
services:

  web:
    ports:
    - 80
    environment:
    - TITLE=${TITLE:-Coffebreak DEV}
    - COLOR=${COLOR:-yellow}
    labels:
      - traefik.frontend.auth.basic=admin:$$1$$I5Kt8BwT$$G4y6mBV3xVzyZKUECxqV61
    image: web:alpine
    # build: .

  mydb:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=secret
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    - vipdb:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080
volumes:
  vipdb:

networks:
  default:
    name: infra