version: '3.9'
services:
  web:
    ports:
    - 80
    environment:
    - TITLE=Vacsora mindenk9ne
    - COLOR=magenta
    image: web:v7
    build: .

  mydb:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=secret
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    - vipdb:/var/lib/postgresql/data
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080

volumes:
  vipdb: