version: '3.9'
services:

  traefik:
    image: traefik:1.7-alpine
    command:
      - --retry
      - --rest
      - --docker.domain=lvh.me
      - --docker.network=docker-marc_default
      - --api.dashboard
    labels:
      - "traefik.frontend.rule=Host:traefik.lvh.me"
      - "traefik.port=8080"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    ports:
    - 80
    environment:
    - TITLE=${TITLE:-Coffebreak DEV}
    - COLOR=${COLOR:-yellow}
    labels:
      - traefik.frontend.auth.basic=admin:$$1$$I5Kt8BwT$$G4y6mBV3xVzyZKUECxqV61
    image: web:alpine
    # build: .

  mydb:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=secret
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    - vipdb:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080
volumes:
  vipdb: