version: '3.9'
services:
  proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  
  web:
    ports:
    - 80
    environment:
    - VIRTUAL_HOST=ebed.lvh.me
    - TITLE=Lalyos ebedelhet
    - COLOR=hotpink
    image: web:alpine
    # build: .

  mydb:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=secret
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    - vipdb:/var/lib/postgresql/data
    
  adminer:
    environment:
      - VIRTUAL_HOST=adminer.lvh.me
    image: adminer
    restart: always
    ports:
      - 8080

volumes:
  vipdb: