version: '3.9'
services:

  traefik:
    image: traefik:1.7-alpine
    command:
      - --retry
      - --rest
      - --docker.domain=lvh.me
      - --docker.network=infra
      - --api.dashboard
    labels:
      - "traefik.frontend.rule=Host:traefik.lvh.me"
      - "traefik.port=8080"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: infra 